CC = gcc
LIBPARSER = ../parser
CFLAGS = -Wall -I$(LIBPARSER)
LDFLAGS = -L$(LIBPARSER) -lparser

all: udp_csum

udp_csum: udp_csum.o onec.o
	$(CC) $^ $(LDFLAGS) -o $@

udp_csum.o: udp_csum.c onec.h
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f udp_csum *.o

.PHONY: all clean
