CC = gcc
LIBPARSER = ../parser
CFLAGS = -Wall -I$(LIBPARSER)
LDFLAGS = -L$(LIBPARSER) -lparser

all: tcp_csum

tcp_csum: tcp_csum.o onec.o
	$(CC) $^ $(LDFLAGS) -o $@

tcp_csum.o: tcp_csum.c onec.h
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f tcp_csum *.o

.PHONY: all clean
