CC = gcc
LIBPARSER = ../parser
CFLAGS = -Wall -I$(LIBPARSER)
LDFLAGS = -L$(LIBPARSER) -lparser

all: icmp_csum

icmp_csum: icmp_csum.o onec.o
	$(CC) $^ $(LDFLAGS) -o $@

icmp_csum.o: icmp_csum.c onec.h
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f icmp_csum *.o

.PHONY: all clean
