CC = gcc
CFLAGS = -Wall
LDFLAGS = 

all: ip_csum

ip_csum: ip_csum.o onec.o parser.o
	$(CC) $^ $(LDFLAGS) -o $@

ip_csum.o: ip_csum.c onec.h parser.h
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f ip_csum *.o

.PHONY: all clean
