CC = gcc
CFLAGS = -Wall
LDFLAGS = 

all: tcp_csum

tcp_csum: tcp_csum.o onec.o parser.o
	$(CC) $^ $(LDFLAGS) -o $@

tcp_csum.o: tcp_csum.c onec.h parser.h
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f tcp_csum *.o

.PHONY: all clean
