CC = gcc
CFLAGS = -Wall
LDFLAGS = 

all: udp_csum

udp_csum: udp_csum.o onec.o parser.o
	$(CC) $^ $(LDFLAGS) -o $@

udp_csum.o: udp_csum.c onec.h parser.h
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f udp_csum *.o

.PHONY: all clean
