CC = gcc
CFLAGS = -Wall
LDFLAGS = 

all: icmp_csum

icmp_csum: icmp_csum.o onec.o parser.o
	$(CC) $^ $(LDFLAGS) -o $@

icmp_csum.o: icmp_csum.c onec.h parser.h
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f icmp_csum *.o

.PHONY: all clean
